sudo: required
services:
  - docker

before_install:
  - docker build -t yevheniibereziuk/docker-react-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true yevheniibereziuk/docker-react-practice npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend-env"
  env: "Frontend-env-env"
  bucket_name: "elasticbeanstalk-us-east-1-851725311536"
  bucket_path: "frontend-env"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"