sudo: required
services:
  - docker
before_install:
  - docker build -t  yevheniibereziuk/docker-react-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true yevheniibereziuk/docker-react-practice npm run test